### ISSUE TITLE
Add wrapper helper

### ISSUE THREAD

**Issue by whitecolor** [cyclejs/isolate#7]
Well just as Idea to reduce boilerplate)

Add `wrap` shortcut helper to `isolate`

```javascript
isolate.wrap = (dataflowComponent) => {
  return function(){
    return isolate(dataflowComponent).apply(undefined, arguments)
  }
}
```

That would allow such use case:
```javascript
import isolate from '@cycle/isolate'
// create auto isolated dataflow 
const GetUser = isolate.wrap(({HTTP, id$}) => {
 . ....
})
```

I use such wrapper when need to create auto isolated version (often components require to be always isolated for correct work)

WDYT?

**Comment by staltz** [comment]
Isn't this the same as

```js
import isolate from '@cycle/isolate'

const GetUser = isolate(({HTTP, id$}) => {
  //  ...
})
```

**Comment by whitecolor** [comment]
Well, no, because this will create SINGLE isolated version (for one scope), so if used multiple times (esp at the same momemet) scope will always be the same, which is probably no good.

**Comment by staltz** [comment]
Well, because `wrap` is anyway just one line
```js
(comp) => (...args) => isolate(comp).apply(null, args)
```

I don't think we will be supporting this API.

Thanks for the idea, but sorry for closing.

**Comment by whitecolor** [comment]
Ah ok) shortcut is good
